<?php include 'header.phtml'; ?>

<div class="actions-title"><p>Un projet au service du bien commun</p></div>
<div class="actions flex">
    
    <div class="left">
        <!--image slider start-->
        <div class="slider">
            <div class="slides">
                <!--radio buttons start-->
                <input type="radio" name="radio-btn" id="radio1">
                <input type="radio" name="radio-btn" id="radio2">
                <input type="radio" name="radio-btn" id="radio3">
                <!--radio buttons end-->
                <!--slide images start-->
                <div class="slide first">
                    <img src="images/maraude.jpg" alt="">
                </div>
                <div class="slide">
                    <img src="images/CleanDay1.JPG" alt="">
                </div>
                <div class="slide">
                    <img src="images/Clean1.jpg" alt="">
                </div>
                <!--slide images end-->
                <!--automatic navigation start-->
                <div class="navigation-auto">
                <div class="auto-btn1"></div>
                <div class="auto-btn2"></div>
                <div class="auto-btn3"></div>
                </div>
                <!--automatic navigation end-->
            </div>
            <!--manual navigation start-->
            <div class="navigation-manual">
                <label for="radio1" class="manual-btn"></label>
                <label for="radio2" class="manual-btn"></label>
                <label for="radio3" class="manual-btn"></label>
            </div>

            <script type="text/javascript">
            var counter = 1;
            setInterval(function(){
            document.getElementById('radio' + counter).checked = true;
            counter++;
            if(counter > 4){
                counter = 1;
            }
            }, 5000);
            </script>
        </div>
    </div>
    <div class="right">
        <p><span>Fédérer et rassembler une communauté :</span> L’art et les actes citoyens sont tous deux fédérateurs, vecteurs d’inspirations et incitent à la rencontre. C’est pourquoi, au travers de nos réalisations et de nos participations collectives, nous souhaitons aller à votre rencontre, pour ensemble, écrire le monde de demain.
        </p>

        <p>Au travers de ce projet nous souhaitons nous impliquer en tant qu'équipe mais aussi faire participer les personnes qui nous suivent.
        Pour soutenir le projet rien de plus simple : <br><br>
        - Partager sur les réseaux sociaux <br>
        - Acheter les EP / Album en digital<br>
        - Acheter le vinyle<br>
        - Écouter du streaming<br>
        - Participer à nos action citoyenne</p><br>

        <p>Nous avons collaborer avec :</p><br>
        <div class="collab">
            <div>
                <img src="images/engagement87.jpg" alt="">
                <p>Engagement 87 Nantes</p>
            </div>  
            <div>
                <img src="images/hebdoEcolo.png" alt="">
                <p>Hebdo Ecolo</p>
            </div>
        </div>
    </div>
    
</div>

