<?php include 'header.phtml'; ?>

<main id="biography" class="containerBio">

	<div class="flex">
		<img src="images/Spotify2.jpg" alt="Humana Project">
		<div id="text">
			<p>Humana Project est un projet artistique gravitant autour de la musique électronique et des arts. Son objectif est simple : développer une audience et une communauté soudée pour réaliser et financer des actions environnementales et solidaires grâce aux fonds récoltés par la vente de vinyles et la vente digitale
			Humana Project souhaite véhiculer son message, à travers ses évènements, performances et concerts.
			<br>
			<br>Le projet entreprend de bâtir un univers auditif et visuel riche et cohérent, pour y faire parvenir une note de poésie et d’engagement militant.
			<br>Symbole de cette initiative, ce personnage à l’allure de conteur, ajoute une touche de mystère et de fantaisie à son récit nuancé.
			<br><br>De part ses histoires et ses ambiances sonores, il tend à amener le public dans une rêverie, une balade à la rencontre de soi-même.
			La musique électronique souvent abstraite et ressentie de façon personnelle se voit guidée par un fil conducteur, qui prend racine dans des valeurs humanistes et élémentaires.
			Au travers de ce mode de communication, il puise ses influences aussi bien en musique classique et traditionnelle, qu’en musique électronique en tout genre. Il s’épanouit dans la musique techno mais n’hésite pas à étendre ses frontières créatives pour donner naissance à de nouvelles réalisations.
			</p>
		</div>
	</div>
      
</main>