<?php include 'header.phtml'; ?>

<main id="discography">
	<div class="containerDisc">
		<div class="card">
			<div class="imgDisc">
				<img src="images/fondhome-desert.jpg" alt="Desert of Complaints">
			</div>
			<div class="contentDisc">
				<h2>Desert of Complaints</h2>
				<p>1 - Intro - On The Other Side</p>
				<p>2 - The Hill</p>
				<p>3 - Mirage</p>
				<p>4 - Behind The Arches</p>
				<p>5 - Virtuous Temple</p>
			</div>
		</div>

		<div class="card">
			<div class="imgDisc">
				<img src="images/EP-miniature.jpg" alt="Résonance">
			</div>
			<div class="contentDisc">
				<h2>Résonance</h2>
				<p>1 - Résonance</p>
				<p>2 - Quantique</p>
				<p>3 - Transcendance</p>
				<p>4 - Symbiotique</p>
			</div>
		</div>

		<div class="card">
			<div class="imgDisc">
				<img src="images/Album1.png" alt="Entre rêve et matière">
			</div>
			<div class="contentDisc">
				<h2>Entre rêve et matière</h2>
				<div class="flex">
				<div>
					<p>1 - Prologue </p>
					<p>2 - La Graine</p>
					<p>3 - Premiere Larme</p>
					<p>4 - Kassiopeia</p>
					<p>5 - Brise Maternelle</p>
					<p>6 - Le Reve</p>
					<p>7 - Capricieuse Reverie</p>
					<p>8 - Eleas-s Dream</p>
					<p>9 - My Ghost</p>
					<p>10 - Le Reflet Des Formes</p>
				</div>
				<div>
				<p>11 - Crazy Money</p>
				<p>12 - Nouvelle Air P1</p>
				<p>13 - Nouvelle Air P2</p>
				<p>14 - Our Home</p>
				<p>15 - La Matiere</p>
				<p>16 - Part Dela La Matiere</p>
				<p>17 - Là-Haut</p>
				<p>18 - Interstellaire</p>
				<p>19 - Epilogue</p>
				</div>
				</div>
				
			</div>
		</div>
	</div>
</main>