<footer id="footer" class="">
    <div class="footer-img">
        <img src="images/logo.png" alt="logo Humana Project">
    </div>

    <div class="footer-content">
        <p>Humana Project</p>
        <p> We are writing this story together !
            Les lignes de cette aventure renforcent nos liens et tendent à nous tirer mutuellement vers le haut.
            Halte au cynisme et à la compétitivité.
            Mettons en valeur les initiatives bienveillantes, afin de nous inspirer mutuellement.
            Chacun de nos actes dessine l’avenir. A nous de choisir le tracé de celui-ci...</p>
    </div>

    <div class="footer-nav">
        <p class="footer-title">Navigation</p>
        <ul>
            <li><a href="asso.php">Qui sommes-nous ?</a></li>
            <li><a href="nos_actions.php">Nos Actions</a></li>
            <li><a href="vos_actions.php">Vos Actions</a></li>
            <li><a href="contact_asso.php">Contact</a></li>
        </ul>
    </div>

    <div class="footer-infos">
        <p class="footer-title">Contact</p>
        <p><i class="fa fa-envelope"></i> contact@humana-project.fr</p>
        <a href="https://www.facebook.com/HumanaProjectMusic/" target="_blank"><i class="fa fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/humana.project/" target="_blank"><i class="fa fa-instagram"></i></a>
    </div>
</footer>