<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Humana Project</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Aladin" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="css/lightbox.min.css">
</head>
<body>
	<header>
		<nav id="nav">

			<a href="../index.php"><img src="images/logo.png" class="grow" alt="HumanaProjectLogo"></a>

			<ul class="flex">
				<li><a href="home.php">Accueil</a></li>			
				<li><a href="biography.php">Biographie</a></li>			
				<li><a href="discography.php">Discographie</a></li>		
				<li><a href="medias.php">Médias</a></li>
				<li><a href="music.php">Musiques</a></li>
				<li><a href="boutique.php">Boutique</a></li>			
				<li><a href="partners.php">Collaborations</a></li>	
				<li><a href="contact.php">Contact</a></li>
				<li><a href="actions.php">Actions</a></li>
				<li><a href="dons.php">Dons</a></li>
			</ul>
		</nav>


		<nav class="small-nav">
			<a class="btn" href="https://www.facebook.com/HumanaProjectMusic/" target="_blank"><i class="fab fa-facebook-f"></i></a>
			<a class="btn" href="https://www.youtube.com/channel/UC5llNt3ntkpfdqRHSIBOu5Q" target="_blank"><i class="fab fa-youtube"></i></a>
			<a class="btn" href="https://soundcloud.com/humanaproject" target="_blank"><i class="fab fa-soundcloud"></i></a>
			<a class="btn" href="https://www.instagram.com/humana.project/" target="_blank"><i class="fab fa-instagram"></i></a>
			<a class="btn" href="https://open.spotify.com/artist/03wiwmLoE9QGXT7dJPZBJQ" target="_blank"><i class="fab fa-spotify"></i></a>
		</nav>
		
			<div class="burger">
					<svg width="80" height="80">
						<path d="M0,5 60,5" stroke="#fff" stroke-width="7"/>
						<path d="M0,23 60,23" stroke="#fff" stroke-width="7"/>
						<path d="M0,42 60,42" stroke="#fff" stroke-width="7"/>
					</svg>
			</div>

			<div id="side-menu" class="side-nav">
				<a href="home.php">Accueil</a>
				<a href="biography.php">Biographie</a>
				<a href="discography.php">Discographie</a>
				<a href="medias.php">Médias</a>
				<a href="music.php">Musiques</a>
				<a href="boutique.php">Boutique</a>
				<a href="partners.php">Collaborations</a>
				<a href="contact.php">Contact</a>
			</div>
			
			
		


		<div class="clear"></div>

		<div class="background"></div>
	</header>

	<script src="js/main.js"></script>
