<?php include 'header.phtml'; ?>

<main id="login">
	<div class="login-page">
		<div class="form">
			<form method="post" action="login.php">
			<?php include 'errors.php'; ?>

				<input type="text" placeholder="Username" name="username">
				<input type="password" placeholder="Password" name="password">
				<button type="submit" name="login_user">Login</button>
				<p class="message">Not Registered? <a href="register.php"> Register</a></p>
			</form>

			  

</main>

