<?php include 'header.phtml'; ?>

<main id="medias" class="container3">

		<div class="gallery">
			<a href="../public/images/pic7.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic7.jpg" alt="photographie festival"></a>

			<a href="../public/images/pic9.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic9_small.jpg" alt="photographie festival"></a>

			<a href="../public/images/pic8.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic8.jpg" alt="photographie festival"></a>
			
			<a href="../public/images/pic1.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic1_small.jpg" alt="photographie forêt 1"></a>

		    <a href="../public/images/pic2.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic2_small.jpg" alt="photographie forêt 2"></a>

		    <a href="../public/images/pic3.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic3.jpg" alt="photographie forêt 3"></a>

		    <a href="../public/images/pic4.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic4_small.jpg" alt="mastering"></a>

		    <a href="../public/images/pic5.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic5_small.jpg" alt="photographie forêt 4"></a>

		    <a href="../public/images/pic6.jpg" data-lightbox="mygallery"><img class="grow" src="images/pic6_small.jpg" alt="photographie forêt 5"></a>
		</div>
			

	
		<div id="video" class="flex">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/n8gZ_A5ptJM" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

			<iframe width="560" height="315" src="https://www.youtube.com/embed/C2EOxHLnEoY" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</div>




	</main>
	<script src="js/lightbox-plus-jquery.min.js"></script>
	<script src="js/main.js"></script>