<?php include 'header.phtml'; ?>

<main id="music" class="container">

	<div id="stream">
		<iframe src="https://Wiseband.lnk.to/Humana-Project-The-Desert-of-ComplaintsWE/widget?size=300x300" width="300" height="300"></iframe>

		<iframe src="https://Wiseband.lnk.to/Humana-Project-ResonanceWE/widget?size=300x300" width="300" height="300" frameborder="0" allowtransparency="true" scrolling="no"></iframe>

		<iframe src="https://Wiseband.lnk.to/Tome-I-Entre-Reve-Et-MatiereWE/widget?size=300x300" width="300" height="300" frameborder="0" allowtransparency="true" scrolling="no"></iframe>
	</div>	

	<div id="tracks">
		<h2>Free Downloads</h2>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/853723783%3Fsecret_token%3Ds-NQnDjCiFStV&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Far-West.rar">Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/816246493%3Fsecret_token%3Ds-70NkIvvPCpI&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/L'oiseau-en-cage.rar">Download</a></div>
		
		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/631580325&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>		<div><a href="download/Vagabond.wav">Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/523119231&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/SubFamilyJam-SmokedStoep-HumanaProjectRemix.wav">Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348035110&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Swiftness.wav">Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348037698&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Earth-Moaning.wav"><span></span>Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348882271&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Pantera.wav"><span></span>Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/362133482&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/L'oiseau-dargent.wav"><span></span>Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348228103&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Glitch-Forest.wav"><span></span>Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348715492&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Shaya.wav"><span></span>Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348089825&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Kundalini.wav"><span></span>Download</a></div>

		<iframe height="166" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/348388310&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<div><a href="download/Le-Mat.wav">Download</a></div>
	</div>

	

</main>