<?php include 'header.phtml'; ?>

<main id="partners">
	<div class="container2">
		<div class="cards">
			<div class="imgBx">
				<img src="images/Charlotte_Davy.jpg" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Charlotte Davy<br><span>Vidéaste</span></h2>
					<ul class="social_icons">
						<li><a href="https://www.instagram.com/chatperlipaupette/" target="_blank"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="cards">
			<div class="imgBx">
				<img src="images/Sandrine_Gergaud.PNG" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Sandrine Gergaud<br><span>Peintre</span></h2>
					<ul class="social_icons">
						<li><a href="https://www.instagram.com/sand.et.ses.peintures/" target="_blank"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="cards">
			<div class="imgBx">
				<img src="images/Adele2.jpg" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Von Naher<br><span>Dessinatrice</span></h2>
					<ul class="social_icons">
						<li><a href="https://www.instagram.com/von_naher/" target="_blank"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="cards">
			<div class="imgBx">
				<img src="images/Halan_Leduc2.jpg" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Halan Leduc<br><span>Harpiste</span></h2>
					<ul class="social_icons">
						<li><p><small><i class="far fa-envelope"></i> leduch2@hotmail.fr </small></p></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="cards">
			<div class="imgBx">
				<img src="images/morganZ.jpg" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Zel Morgan<br><span>Dessinatrice</span></h2>
					<ul class="social_icons">
						<li><a href="https://www.instagram.com/_zelmorgan_/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="cards">
			<div class="imgBx">
				<img src="images/morganeD.png" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Morgane<br><span>Photographe & Vidéaste</span></h2>
					<ul class="social_icons">
						<li><a href="https://urlz.fr/e6Jl" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="cards">
			<div class="imgBx">
				<img src="images/guiom.jpg" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Guiom Créations<br><span>Peintre & créateur</span></h2>
					<ul class="social_icons">
						<li><a href="https://www.facebook.com/guiom.pino" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="https://www.instagram.com/guillaume417/" target="_blank"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="cards">
			<div class="imgBx">
				<img src="images/TilleulAtelier.jpg" alt="">
			</div>
			<div class="content">
				<div class="details">
					<h2>Tilleul Atelier<br><span>Couturière</span></h2>
					<ul class="social_icons">
						<li><a href="https://www.facebook.com/TilleulAtelier" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="https://www.instagram.com/atelier_tilleul/" target="_blank"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</main>
